pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = credentials('docker-cred-id')
        DOCKER_IMAGE = 'taniajose95/nodejs_docker'
        DOCKER_REGISTRY = "${env.DOCKER_REGISTRY}"
    }

    stages {
        stage('Clone Repository') {
            steps {
	        git branch: 'main', url: 'https://github.com/taniajose95/my_jenkins_portfolio.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('docker_jenkins_pipeline') {
                    script {
                        docker.build("${DOCKER_IMAGE}:${env.BUILD_ID}")
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('docker_jenkins_pipeline') {
                    script {
                        docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").inside('--user root') {
                            sh 'npm install --only=dev'
			    sh 'npm test'
                        }
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('docker_jenkins_pipeline') {
                    script {
                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
                            docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").push()
                            docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").push("latest")
                        }
                    }
                }
            }
        }

        stage('Deploy Docker Container') {
            steps {
                dir('docker_jenkins_pipeline') {
                    sh 'docker-compose up -d'
                }
            }
        } 
  }
}
