pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = credentials('docker-cred-id')
        DOCKER_IMAGE = 'taniajose95/nodejs_docker:latest'
        DOCKER_REGISTRY = "${env.DOCKER_REGISTRY}"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/taniajose95/my_jenkins_portfolio.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${env.BUILD_ID}")
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").inside {
                        sh 'npm test'
                    }
                }
            }
        }

        stage('Deploy Docker Container') {
            steps {
                script {
                    docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
                        docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").push()
                    }
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}
